# Generated by Django 5.2.4 on 2025-07-31 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(unique=True)),
                ('capacity', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[(1, '12:00 pm - 1:00 pm'), (2, '1:00 pm - 2:45 pm'), (3, '3:00 pm - 4:00 pm'), (4, '7:00 pm -8:45 pm'), (5, '9:00 pm - 10:45 pm')], max_length=5)),
                ('number_of_guests', models.PositiveIntegerField(default=2)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_customer', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_booking', to='booking.table')),
            ],
            options={
                'ordering': ('date', 'time'),
                'unique_together': {('table', 'date', 'time')},
            },
        ),
    ]
