# Generated by Django 5.2.4 on 2025-08-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_unique_together_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
