# Generated by Django 5.2.4 on 2025-08-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_delete_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[('12:00', '12:00 pm - 1:00 pm'), ('1:00', '1:00 pm - 2:45 pm'), ('3:00', '3:00 pm - 4:00 pm'), ('7:00', '7:00 pm -8:45 pm'), ('9:00', '9:00 pm - 10:45 pm')], default=1),
        ),
    ]
