# Generated by Django 5.2.4 on 2025-08-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[(1, '12:00 pm - 1:00 pm'), (2, '1:00 pm - 2:45 pm'), (3, '3:00 pm - 4:00 pm'), (4, '7:00 pm -8:45 pm'), (5, '9:00 pm - 10:45 pm')], default=1),
        ),
    ]
