# Generated by Django 5.2.4 on 2025-07-23 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('salads', 'Salads'), ('cocktails', 'Cocktails'), ('wine', 'Wine'), ('desserts', 'Desserts'), ('chefs special', "Chef's Special")], default='starter', max_length=50)),
                ('description', models.TextField(default='')),
                ('price', models.FloatField(default=0.0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu')),
            ],
        ),
    ]
