# Generated by Django 5.2.4 on 2025-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('cocktails', 'Cocktails'), ('wine', 'Wine'), ('desserts', 'Desserts'), ('chefs special', "Chef's Special")], default='starter', max_length=50),
        ),
    ]
